version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - stripe-network

  app:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "5007:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    networks:
      - stripe-network

volumes:
  bundle_data:
  mysql_db:


networks:
  stripe-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
